trigger: none
pool:
  name: fk-agent

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
    backendServiceArm: 'fk-sc'
    backendAzureRmStorageAccountName: 'fkstg'
    backendAzureRmContainerName: 'fkcontainer'
    backendAzureRmKey: 'dev.statefile'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
    environmentServiceNameAzureRM: 'fk-sc'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)\environment\dev'
    environmentServiceNameAzureRM: 'fk-sc'

